### PR TITLE
Add Syscfg config line for mobile_ppp connections

### PR DESCRIPTION
**Pull request by The-Compiler**
This makes it possible to set more modem-specific options, e.g. to turn on roaming.

### CODE REVIEW

**Comment by The-Compiler** [comment]
> If roaming is what you are after, we could add something like Roaming= parameter that defaults to no.

I thought about this (and yes - that was my original motivation), but I'm also unsure about the other defaults in that line. For example, the last value sets:

```
0=Circuit-Switched only
1=Packet-Switched only
2=Circuit- & Packet-Switched
3=Any
4=no Change
```

to "packet-switched only". Do you know what the rationale for setting that is?

> For full flexibility, we could add something like ATCustom= which would be added more or less verbatim to the chatscript ("'OK' 'AT$ATCustom'").

Sounds good - though at which point would it be sent?

> Of course, this would also require a way to suppress the effect of Mode=.

Isn't `Mode=None` that already?

**Comment by joukewitteveen** [comment]
> Do you know what the rationale for setting that is?

No, maybe @zoqaeski does.

>> `ATCustom=`
>
> Sounds good - though at which point would it be sent?

Not really, this is the least favorable option as it reduces the abstraction of netctl. In netctl, options should reflect meaningful concepts of high-level network set-up, not specifics for connection tools. `Mode=SYSCFG=...` is already a departure from that, but at least has a limited scope.

If `ATCustom=` is to be used for setting a `AT^SYSCFG` string, it supposedly goes right above setting the access point. Again, I am not convinced that `ATCustom=` is the way to go.

>> Of course, this would also require a way to suppress the effect of Mode=.
>
> Isn't Mode=None that already?

Ah, right, this turns the mode string into a no-op (`'OK' 'AT'`). This would benefit from a comment in the code.

**Comment by The-Compiler** [comment]
Updated with your `Mode=SYSCFG=...` proposal.

As for abstracting over things: I don't think this is possible with subtle differences in different modems. I already need `Init='ATQ0 V1 E1 S0=0'` in my config for *anything* to work with mine :wink:

**Comment by zoqaeski** [comment]
IIRC I based this profile on that entry in the Arch wiki, and I also had a Huawei reference document for their modems that detailed what each AT code did. Part of the problem I found back then is that each modem initiates a connection differently, and they all use some kind of proprietary voodoo magic piggybacked on the AT codes. [Here's the manual](https://drive.google.com/open?id=0B15PFrY7neryZlpRdFRCdEJoek0)—I don't remember where I found it, and it's about 10 years old. A quick search found [a newer, similar manual](http://download-c.huawei.com/download/downloadCenter?downloadId=15779).

It never really worked reliably for me then, and in the end I gave up and bought a wireless modem that connected to the mobile broadband network but presented itself as a wireless AP.

**Comment by The-Compiler** [comment]
FWIW it's working very reliably for the Huawei ME906s in my Thinkpad X1 Yoga, with the custom `Init` line mentioned above. It looks like every modem has its own command specification though - [here's mine](http://consumer.huawei.com/en/solutions/m2m-solutions/products/support/user-guides/detail/me906s-158-en.htm?id=51047)

**Comment by joukewitteveen** [comment]
Thanks! I pulled your patch as e49fa190c1f20cb8d305e876141566d4c2081cc7.
In a follow-up commit I corrected formatting of the man page because your quotations did not come out nicely. Please test your patches (in this case: check the 'compiled' manpages) more in the future.

I am sorry it took me so long to pull this. Shortly before this PR, netctl 1.13 was released. As this is a big release, I expect some issues to surface once it hits the Arch Linux [core] repository. However, it is delayed by systemd 233, which is still not in [core].

The new `SYSCFG=` options will be available starting with netctl 1.14, which could take a few months. Until then, I noticed that there is a workaround as follows (mind the single quotes):
```
Init="ATQ0 V1 E1 S0=0'
'OK' 'AT\^SYSCFG=..."
Mode=none
```

**Pull request closed without merging**
